apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-kardex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tingeso-kardex
  template:
    metadata:
      labels:
        app: tingeso-kardex
    spec:
      containers:
      - name: tingeso-kardex
        image: tingeso-kardex-service:latest
        imagePullPolicy: Never
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
