apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-auth
spec:
  selector:
    matchLabels:
      app: tingeso-auth
  template:
    metadata:
      labels:
        app: tingeso-auth
    spec:
      initContainers: 
      - name: wait-for-mysql
        image: busybox
        # CORRECCIÓN: Usamos 'mysql-service' que es el nombre del Service de K8s
        command: ['sh', '-c', 'until nc -z -v -w30 mysql-service 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
      - name: tingeso-auth
        image: demishuaccha/tingeso-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service.default.svc.cluster.local:8888"
        
        # 1. URL DE LA BASE DE DATOS
        # Apuntamos al servicio de MySQL y a la base de datos creada en el init script
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/auth_db"

        # 2. CREDENCIALES ESTÁNDAR (Para evitar fallos si el Config Server tarda)
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_auth
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_auth
        
        # 3. REGISTRO EN EUREKA
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"

        # 4. PROBES PARA ESTABILIDAD
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-auth
spec:
  selector:
    app: tingeso-auth
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP