apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-auth
spec:
  selector:
    matchLabels:
      app: tingeso-auth
  template:
    metadata:
      labels:
        app: tingeso-auth
    spec:
      initContainers:
      - name: wait-for-infrastructure
        image: busybox
        # ESPERA ACTIVA PARA MYSQL Y EL CONFIG-SERVICE
        command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888; do echo "Esperando infraestructura..."; sleep 5; done;']
      containers:
      - name: tingeso-auth
        image: demishuaccha/tingeso-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        
        # IMPORTACIÓN DE CONFIGURACIÓN (DNS interno de Kubernetes)
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
        
        # 1. HOST DE LA BASE DE DATOS (Sincronizado con ${MYSQL_HOST} en auth.yaml)
        - name: MYSQL_HOST
          value: "mysql-service"

        # 2. CREDENCIALES (Nombres exactos para el mapeo con el Config Server)
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_auth
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_auth
        
        # 3. HOST DE EUREKA (Sincronizado con ${EUREKA_HOST} en auth.yaml)
        - name: EUREKA_HOST
          value: "eureka-service"

        # 4. SONDAS DE SALUD (PROBES)
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40 # Tiempo de gracia para el arranque de Spring Boot
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 70
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-auth
spec:
  selector:
    app: tingeso-auth
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP