apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-client
spec:
  selector:
    matchLabels:
      app: tingeso-client
  template:
    metadata:
      labels:
        app: tingeso-client
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        # CORRECCIÓN: Apuntamos al nombre del servicio 'mysql-service'
        command: ['sh', '-c', 'until nc -z -v -w30 mysql-service 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
      - name: tingeso-client
        image: demishuaccha/tingeso-client-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service.default.svc.cluster.local:8888"
        
        # 1. URL DE LA BASE DE DATOS (Inyectada directamente)
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/client_db"

        # 2. CREDENCIALES ESTÁNDAR DE SPRING (Extraídas de tus secrets)
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_client
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_client
        
        # 3. CONEXIÓN A EUREKA
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"

        # 4. PROBES PARA ASEGURAR DISPONIBILIDAD
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-client
spec:
  selector:
    app: tingeso-client
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP