apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-client
spec:
  selector:
    matchLabels:
      app: tingeso-client
  template:
    metadata:
      labels:
        app: tingeso-client
    spec:
      initContainers:
      - name: wait-for-infrastructure
        image: busybox
        # ESPERA ACTIVA PARA MYSQL Y EL CONFIG-SERVICE
        command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888; do echo "Esperando infraestructura..."; sleep 5; done;']
      containers:
      - name: tingeso-client
        image: demishuaccha/tingeso-client-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        
        # IMPORTACIÓN DE CONFIGURACIÓN (DNS simplificado)
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
        
        # 1. HOST DE LA BASE DE DATOS (Mapea con ${MYSQL_HOST} en client.yaml)
        - name: MYSQL_HOST
          value: "mysql-service"

        # 2. CREDENCIALES (Nombres exactos para el mapeo con el Config Server)
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_client
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_client
        
        # 3. HOST DE EUREKA (Sincronizado con ${EUREKA_HOST} en client.yaml)
        - name: EUREKA_HOST
          value: "eureka-service"

        # 4. SONDAS DE SALUD (PROBES)
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40 
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 70
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-client
spec:
  selector:
    app: tingeso-client
  ports:
  - port: 8080
    targetPort: 8080
    readinessProbe:
        httpGet:
            path: /actuator/health
            port: 8080
        initialDelaySeconds: 40 # Dale tiempo a Spring para arrancar
        periodSeconds: 10
    livenessProbe:
        httpGet:
            path: /actuator/health
            port: 8080
        initialDelaySeconds: 60
        periodSeconds: 20
  type: ClusterIP