apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-fee
spec:
  selector:
    matchLabels:
      app: tingeso-fee
  template:
    metadata:
      labels:
        app: tingeso-fee
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        # Corregido: apuntamos a mysql-service que es el nombre del Service de K8s
        command: ['sh', '-c', 'until nc -z -v -w30 mysql-service 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
      - name: tingeso-fee
        image: demishuaccha/tingeso-fee-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service.default.svc.cluster.local:8888"
        
        # URL de la base de datos (Usando el host del ConfigMap y la DB del init script)
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/fee_db"

        # Credenciales usando los nombres que Spring Boot reconoce por defecto
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_fee
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_fee
        
        # Para que se encuentre con Eureka correctamente
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-fee
spec:
  selector:
    app: tingeso-fee
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP