apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-fee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tingeso-fee
  template:
    metadata:
      labels:
        app: tingeso-fee
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 mysql-service 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
      - name: tingeso-fee
        image: demishuaccha/tingeso-fee-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_fee
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_fee
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://${MYSQL_HOST}:3306/tingeso_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-fee
spec:
  selector:
    app: tingeso-fee
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
