apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-kardex
spec:
  selector:
    matchLabels:
      app: tingeso-kardex
  template:
    metadata:
      labels:
        app: tingeso-kardex
    spec:
      initContainers:
      - name: wait-for-infrastructure
        image: busybox
        # AHORA ESPERA A MYSQL Y AL CONFIG-SERVICE SIMULTÁNEAMENTE
        command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888; do echo "Esperando MySQL y Config Service..."; sleep 5; done;']
      containers:
      - name: tingeso-kardex
        image: demishuaccha/tingeso-kardex-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        
        # IMPORTACIÓN DE CONFIGURACIÓN (DNS simplificado para el clúster)
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
        
        # 1. HOST DE BASE DE DATOS (Mapea con ${MYSQL_HOST} en tu kardex.yaml de config-data)
        - name: MYSQL_HOST
          value: "mysql-service"

        # 2. CREDENCIALES (Nombres exactos que pusimos en el archivo de configuración externa)
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_kardex
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_kardex
        
        # 3. HOST DE EUREKA (Mapea con ${EUREKA_HOST} en el YAML centralizado)
        - name: EUREKA_HOST
          value: "eureka-service"

        # 4. PROBES DE SALUD (ACTUATOR)
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40 # Tiempo prudente para el arranque de Spring Boot
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 70
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-kardex
spec:
  selector:
    app: tingeso-kardex
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP