apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-kardex
spec:
  selector:
    matchLabels:
      app: tingeso-kardex
  template:
    metadata:
      labels:
        app: tingeso-kardex
    spec:
      initContainers:
      - name: wait-for-infrastructure
        image: busybox
        # ESPERA A MYSQL Y AL CONFIG-SERVICE
        command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888; do echo "Esperando MySQL y Config Service..."; sleep 5; done;']
      containers:
      - name: tingeso-kardex
        image: demishuaccha/tingeso-kardex-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_kardex
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_kardex
        - name: EUREKA_HOST
          value: "eureka-service"

        # SONDAS DE SALUD EN EL CONTENEDOR (Correcto)
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 70
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-kardex
spec:
  selector:
    app: tingeso-kardex
  ports:
  - port: 8080
    targetPort: 8080
  # SE ELIMINARON LAS SONDAS DE AQU√ç (No pertenecen al Service)
  type: ClusterIP