apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-loan
spec:
  selector:
    matchLabels:
      app: tingeso-loan
  template:
    metadata:
      labels:
        app: tingeso-loan
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        # CORRECCIÓN: Usamos el nombre del Service de K8s 'mysql-service'
        command: ['sh', '-c', 'until nc -z -v -w30 mysql-service 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
      - name: tingeso-loan
        image: demishuaccha/tingeso-loan-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service.default.svc.cluster.local:8888"
        
        # 1. URL DE LA BASE DE DATOS
        # Asegura la conexión al host del servicio y a la base de datos correcta
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/loan_db"

        # 2. CREDENCIALES ESTÁNDAR DE SPRING BOOT
        # Mapeadas desde el Secret 'mysql-secrets'
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_loan
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_loan
        
        # 3. CONEXIÓN A EUREKA
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"

        # 4. SONDAS DE SALUD (PROBES)
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-loan
spec:
  selector:
    app: tingeso-loan
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP