apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  # --- CREDENCIALES ADMINISTRATIVAS ---
  # root / root
  username: cm9vdA==
  password: cm9vdA==
  
  # --- CREDENCIALES POR SERVICIO ---
  # Formato: usuario / pass_a√±o
  
  # Auth: user_auth / auth_pass_2025
  user_auth: dXNlcl9hdXRo
  pass_auth: YXV0aF9wYXNzXzIwMjU=
  
  # Client: user_client / client_pass_2025
  user_client: dXNlcl9jbGllbnQ=
  pass_client: Y2xpZW50X3Bhc3NfMjAyNQ==
  
  # Fee: user_fee / fee_pass_2025
  user_fee: dXNlcl9mZWU=
  pass_fee: ZmVlX3Bhc3NfMjAyNQ==
  
  # Inventory: user_inventory / inv_pass_2025
  user_inventory: dXNlcl9pbnZlbnRvcnk=
  pass_inventory: aW52X3Bhc3NfMjAyNQ==
  
  # Kardex: user_kardex / kardex_pass_2025
  user_kardex: dXNlcl9rYXJkZXg=
  pass_kardex: a2FyZGV4X3Bhc3NfMjAyNQ==
  
  # Loan: user_loan / loan_pass_2025
  user_loan: dXNlcl9sb2Fu
  pass_loan: bG9hbl9wYXNzXzIwMjU=
  
  # Report: user_report / report_pass_2025
  user_report: dXNlcl9yZXBvcnQ=
  pass_report: cmVwb3J0X3Bhc3NfMjAyNQ==
