apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim  # Este nombre debe coincidir EXACTAMENTE con el del Deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Esto es opcional en Minikube, pero asegura que busque tu PV manual
  storageClassName: "" 
  volumeName: mysql-pv