apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  username: cm9vdA==            # root
  password: cm9vdA==            # root
  user_auth: dXNlcl9hdXRo
  pass_auth: YXV0aF9wYXNzXzIwMjU=
  user_client: dXNlcl9jbGllbnQ=
  pass_client: Y2xpZW50X3Bhc3NfMjAyNQ==
  user_fee: dXNlcl9mZWU=
  pass_fee: ZmVlX3Bhc3NfMjAyNQ==
  user_inventory: dXNlcl9pbnZlbnRvcnk=
  pass_inventory: aW52X3Bhc3NfMjAyNQ==
  user_kardex: dXNlcl9rYXJkZXg=
  pass_kardex: a2FyZGV4X3Bhc3NfMjAyNQ==
  user_loan: dXNlcl9sb2Fu
  pass_loan: bG9hbl9wYXNzXzIwMjU=
  user_report: dXNlcl9yZXBvcnQ=
  pass_report: cmVwb3J0X3Bhc3NfMjAyNQ==