apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-report
spec:
  selector:
    matchLabels:
      app: tingeso-report
  template:
    metadata:
      labels:
        app: tingeso-report
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 mysql-service.default.svc.cluster.local 3306; do echo "Waiting for MySQL..."; sleep 5; done;']
      containers:
      - name: tingeso-report
        image: demishuaccha/tingeso-report-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service.default.svc.cluster.local:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service.default.svc.cluster.local:8761/eureka/"
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_report
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_report
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://${MYSQL_HOST}:3306/tingeso_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-report
spec:
  selector:
    app: tingeso-report
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
