apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-report
spec:
  selector:
    matchLabels:
      app: tingeso-report
  template:
    metadata:
      labels:
        app: tingeso-report
    spec:
      initContainers:
      - name: wait-for-infrastructure
        image: busybox
        # AHORA ESPERA A MYSQL Y AL CONFIG-SERVICE
        command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888; do echo "Esperando infraestructura..."; sleep 5; done;']
      containers:
      - name: tingeso-report
        image: demishuaccha/tingeso-report-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        # Usamos el DNS corto para simplicidad
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
        
        # 1. URL DE LA BASE DE DATOS (Mantenemos el nombre que espera el .yaml de config-data)
        - name: MYSQL_HOST
          value: "mysql-service"

        # 2. CREDENCIALES (Cambiamos los nombres para que coincidan con report.yaml)
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_report
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_report
        
        # 3. CONEXIÃ“N A EUREKA
        - name: EUREKA_HOST
          value: "eureka-service"

        # 4. PROBES DE SALUD
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 40 # Aumentamos un poco para dar tiempo a Java de levantar
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 70
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-report
spec:
  selector:
    app: tingeso-report
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP