apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-report
spec:
  selector:
    matchLabels:
      app: tingeso-report
  template:
    metadata:
      labels:
        app: tingeso-report
    spec:
      initContainers:
      - name: wait-for-infrastructure
        image: busybox
        # ESPERA ACTIVA PARA MYSQL Y EL CONFIG-SERVICE
        command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888; do echo "Esperando infraestructura..."; sleep 5; done;']
      containers:
      - name: tingeso-report
        image: demishuaccha/tingeso-report-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://config-service:8888"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_report
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: pass_report
        - name: EUREKA_HOST
          value: "eureka-service"

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60  
          periodSeconds: 20        
          failureThreshold: 5     
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120 
          periodSeconds: 30        
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-report
spec:
  selector:
    app: tingeso-report
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP