apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tingeso-inventory
  template:
    metadata:
      labels:
        app: tingeso-inventory
    spec:
      containers:
      - name: tingeso-inventory
        image: tingeso-inventory-service:latest
        imagePullPolicy: Never
        env:
          # Identidad para el Config Server
          - name: SPRING_APPLICATION_NAME
            value: "tingesoMS_inventory"
          
          # Indica d칩nde est치 el Config Server dentro de la red de K8s
          - name: CONFIG_SERVER_HOST
            value: "config-service"

          # Correcci칩n del puerto 8888 -> 8081
          - name: SPRING_CONFIG_IMPORT
            value: "optional:configserver:http://config-service:8081"

          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://eureka-service:8761/eureka/"

          # Configuraci칩n de base de datos desde infraestructura
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: host
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: password