apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-fee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tingeso-fee
  template:
    metadata:
      labels:
        app: tingeso-fee
    spec:
      containers:
      - name: tingeso-fee
        image: tingeso-fee-service:latest
        imagePullPolicy: Never
        env:
          # Identidad del servicio
          - name: SPRING_APPLICATION_NAME
            value: "tingesoMS_fee"
          
          # Host para resolver la URL del bootstrap
          - name: CONFIG_SERVER_HOST
            value: "config-service"

          # Puerto 8081 (Config Server)
          - name: SPRING_CONFIG_IMPORT
            value: "optional:configserver:http://config-service:8081"

          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://eureka-service:8761/eureka/"

          # Configuraci√≥n de base de datos desde infraestructura
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: host
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: password