apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tingeso-loan
  template:
    metadata:
      labels:
        app: tingeso-loan
    spec:
      containers:
      - name: tingeso-loan
        image: tingeso-loan-service:latest
        imagePullPolicy: Never
        env:
          # Nombre del servicio para el registro y configuración
          - name: SPRING_APPLICATION_NAME
            value: "tingesoMS_loan"
          
          # Nombre del servicio del Config Server en K8s
          - name: CONFIG_SERVER_HOST
            value: "config-service"

          # Puerto actualizado de 8888 a 8081
          - name: SPRING_CONFIG_IMPORT
            value: "optional:configserver:http://config-service:8081"

          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://eureka-service:8761/eureka/"

          # Configuración de base de datos vinculada a secretos y configMaps
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: host
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: password
